version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - theeca-net

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./theeca-eod-frontend:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start"
    networks:
      - theeca-net

networks:
  theeca-net:
    driver: bridge